spring.application.name=dateevaluation

# Cấu hình kết nối Supabase PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate (JPA)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Vì ta đã tạo bảng bằng SQL ở trên, nên để là 'none' hoặc 'validate'
spring.jpa.hibernate.ddl-auto=none